module.exports = function(grunt) {

  var existsSync = require('fs').existsSync;

  grunt.registerTask('component', 'Build component"', function() {
    if ( !existsSync('Makefile') ){
      grunt.log.errorlns('`Makefile` generated by `component-create` should be placed to make this task to work!');
      return false;
    }
    var done = this.async();
    grunt.utils.spawn({cmd: 'make', args: ['build'] }, function(err, result, code){
        if ( err ) grunt.log.writeln(err);
        done(null, result);
    });
  });
};

